version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ~/.docker/volumes/nextjs/deps:/app/deps
      - ~/.docker/volumes/nextjs/pages:/app/pages
      - ~/.docker/volumes/nextjs/styles:/app/styles
      - ~/.docker/volumes/nextjs/node_modules:/app/node_modules
      - ~/.docker/volumes/nextjs/.next:/app/.next
