import Head from 'next/head';

import Header from '../Components/Header';
import CompetitionCard from '../Components/CompetitionCard';

import { Container } from '../styles/Home';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Header />
        <section>
          <div>
            <h1>
              Seja bem-vindo(a) ao <span>getmoreSports!</span>
            </h1>

            <h4>
              Aqui você terá acesso a classificação e jogos atualizados dos
              principais campeonatos de futebol do mundo.
            </h4>
          </div>

          <img src="/assets/playerIllustration.svg" />
        </section>

        <section>
          <h1>Escolha aqui o campeonato desejado:</h1>

          <CompetitionCard />
          <img src="/assets/logos/serieALogo.png" alt="Série A TIM" />
          <img src="/assets/logos/premierLogoPurple.svg" alt="Premier League" />
          <img src="/assets/logos/brasileiraoLogo.png" alt="Brasileirão" />
        </section>
      </Container>
    </div>
  );
};

export default Home;
